@startuml ArborescenceHierarchique
!pragma layout smetana
!define RECTANGLE class
skinparam class {
    BackgroundColor LightSkyBlue
    ArrowColor Black
    RoundCorner 25
}

RECTANGLE Accueil

RECTANGLE "Liste des Tâches"
RECTANGLE "Détail de la Tâche"
RECTANGLE "Création de Tâche"

RECTANGLE "Profil Utilisateur"
RECTANGLE "Paramètres Utilisateur"

Accueil --> "Liste des Tâches" : Accéder aux tâches
Accueil --> "Profil Utilisateur" : Accéder à mon profil

"Liste des Tâches" --> "Détail de la Tâche" : Consulter une tâche
"Liste des Tâches" --> "Création de Tâche" : Créer une tâche

"Profil Utilisateur" --> "Paramètres Utilisateur" : Gérer paramètres
@enduml
